<?php

return [
    // The number of days elapsed before old activity log entries are deleted.
    'prune_days' => env('APP_ACTIVITY_PRUNE_DAYS', 90),

    // If set to true activity log entries generated by an admin user that is not also
    // a part of the server in question will be hidden from the activity logs API response.
    //
    // Activity will still be properly tracked, just not displayed.
    'hide_admin_activity' => env('APP_ACTIVITY_HIDE_ADMIN', false),

    // The number of days elapsed before old admin activity log entries are deleted.
    // Set to null to disable pruning. Default is 30 days.
    'admin_prune_days' => env('APP_ADMIN_ACTIVITY_PRUNE_DAYS', 30),
];
